### ISSUE TITLE
Did you do the ab study that delete the channel attention?

### ISSUE THREAD

**Issue by splinter21** [dandingbudanding/BAM#3]
CA+SA
only SA
these two experiments

I wonder if CA can improve the preforence.

**Comment by dandingbudanding** [comment]
Yes, BAM is the best result of experimenting with all possible combinations





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dandingbudanding/BAM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月31日(星期天) 晚上9:00
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[dandingbudanding/BAM] Did you do the ab study that delete the CA attention? (Issue #3)





 
CA+SA
 only SA
 these two experiments
 
I wonder if CA can improve the preforence.
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
