### ISSUE TITLE
Where should we put the attention module?

### ISSUE THREAD

**Issue by splinter21** [dandingbudanding/BAM#4]
I read the codes.
Sometimes it's put on the tail of the body (e.g. EDSR, AWSRN).
Sometimes it's put on the tail of base blocks (e.g. RCAN, DRLN).

Why don't you put it on the tail of base blocks of EDSR (Residual block) and AWSRN (AWRU or LFB)? Maybe there would be more increase of performance? 

By the way, AWSRN adds wn before all convolutional layers, but the attention module don't. Maybe this will cause some performance decrease (lr of AWSRN is 1e-3).

**Comment by dandingbudanding** [comment]
BAM is placed randomly just to verify BAM's plug-and-play nature.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dandingbudanding/BAM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月31日(星期天) 晚上9:24
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[dandingbudanding/BAM] Where should we put the attention module? (Issue #4)





 
I read the codes.
 Sometimes it's put on the tail of the body (e.g. EDSR, AWSRN).
 Sometimes it's put on the tail of base block(e.g. RCAN, DRLN).
 
Why don't you put it on the tail of base block of EDSR (Residual block) and AWSRN (AWRU or LFB)? Maybe there would be more increase of performance?
 
By the way, AWSRN adds wn before all convolutional layers, but the attention module don't. Maybe this will cause some performance decrease (lr of AWSRN is 1e-3).
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
