### ISSUE TITLE
I notice that the activation layer of CA is PReLU. Did you do the experiments to compare ReLU with PReLU?

### ISSUE THREAD

**Issue by splinter21** [dandingbudanding/BAM#5]

**Comment by dandingbudanding** [comment]
Didn't.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dandingbudanding/BAM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月31日(星期天) 晚上9:32
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[dandingbudanding/BAM] I notice that the activation layer of CA is PReLU. Did you do the experiments to compare ReLU with PReLU? (Issue #5)





 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
